global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@cs2marketplace.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'console'

receivers:
  - name: 'console'
    # For now, just log to console - you can add email/slack later
    webhook_configs:
      - url: 'http://localhost:9999/webhook'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']