// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: shared/proto/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Rarity        string                 `protobuf:"bytes,6,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Condition     string                 `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"`
	OwnerId       string                 `protobuf:"bytes,8,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IsListed      bool                   `protobuf:"varint,9,opt,name=is_listed,json=isListed,proto3" json:"is_listed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skin) Reset() {
	*x = Skin{}
	mi := &file_shared_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skin) ProtoMessage() {}

func (x *Skin) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skin.ProtoReflect.Descriptor instead.
func (*Skin) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Skin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Skin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skin) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skin) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Skin) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Skin) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Skin) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Skin) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Skin) GetIsListed() bool {
	if x != nil {
		return x.IsListed
	}
	return false
}

type CreateSkinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skin          *Skin                  `protobuf:"bytes,1,opt,name=skin,proto3" json:"skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkinRequest) Reset() {
	*x = CreateSkinRequest{}
	mi := &file_shared_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkinRequest) ProtoMessage() {}

func (x *CreateSkinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkinRequest.ProtoReflect.Descriptor instead.
func (*CreateSkinRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSkinRequest) GetSkin() *Skin {
	if x != nil {
		return x.Skin
	}
	return nil
}

type SkinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skin          *Skin                  `protobuf:"bytes,1,opt,name=skin,proto3" json:"skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkinResponse) Reset() {
	*x = SkinResponse{}
	mi := &file_shared_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinResponse) ProtoMessage() {}

func (x *SkinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinResponse.ProtoReflect.Descriptor instead.
func (*SkinResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *SkinResponse) GetSkin() *Skin {
	if x != nil {
		return x.Skin
	}
	return nil
}

type GetSkinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkinRequest) Reset() {
	*x = GetSkinRequest{}
	mi := &file_shared_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkinRequest) ProtoMessage() {}

func (x *GetSkinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkinRequest.ProtoReflect.Descriptor instead.
func (*GetSkinRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSkinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`     // optional
	IsListed      bool                   `protobuf:"varint,2,opt,name=is_listed,json=isListed,proto3" json:"is_listed,omitempty"` // optional
	Rarity        string                 `protobuf:"bytes,3,opt,name=rarity,proto3" json:"rarity,omitempty"`                      // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkinsRequest) Reset() {
	*x = ListSkinsRequest{}
	mi := &file_shared_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkinsRequest) ProtoMessage() {}

func (x *ListSkinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkinsRequest.ProtoReflect.Descriptor instead.
func (*ListSkinsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ListSkinsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListSkinsRequest) GetIsListed() bool {
	if x != nil {
		return x.IsListed
	}
	return false
}

func (x *ListSkinsRequest) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

type ListSkinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skins         []*Skin                `protobuf:"bytes,1,rep,name=skins,proto3" json:"skins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkinsResponse) Reset() {
	*x = ListSkinsResponse{}
	mi := &file_shared_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkinsResponse) ProtoMessage() {}

func (x *ListSkinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkinsResponse.ProtoReflect.Descriptor instead.
func (*ListSkinsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ListSkinsResponse) GetSkins() []*Skin {
	if x != nil {
		return x.Skins
	}
	return nil
}

type UpdateSkinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skin          *Skin                  `protobuf:"bytes,1,opt,name=skin,proto3" json:"skin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkinRequest) Reset() {
	*x = UpdateSkinRequest{}
	mi := &file_shared_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkinRequest) ProtoMessage() {}

func (x *UpdateSkinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkinRequest.ProtoReflect.Descriptor instead.
func (*UpdateSkinRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSkinRequest) GetSkin() *Skin {
	if x != nil {
		return x.Skin
	}
	return nil
}

type DeleteSkinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkinRequest) Reset() {
	*x = DeleteSkinRequest{}
	mi := &file_shared_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkinRequest) ProtoMessage() {}

func (x *DeleteSkinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkinRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkinRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSkinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_shared_proto_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ToggleListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsListed      bool                   `protobuf:"varint,2,opt,name=is_listed,json=isListed,proto3" json:"is_listed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleListingRequest) Reset() {
	*x = ToggleListingRequest{}
	mi := &file_shared_proto_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleListingRequest) ProtoMessage() {}

func (x *ToggleListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleListingRequest.ProtoReflect.Descriptor instead.
func (*ToggleListingRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *ToggleListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToggleListingRequest) GetIsListed() bool {
	if x != nil {
		return x.IsListed
	}
	return false
}

type TransferOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkinId        string                 `protobuf:"bytes,1,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`
	NewOwnerId    string                 `protobuf:"bytes,2,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnershipRequest) Reset() {
	*x = TransferOwnershipRequest{}
	mi := &file_shared_proto_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnershipRequest) ProtoMessage() {}

func (x *TransferOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnershipRequest.ProtoReflect.Descriptor instead.
func (*TransferOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *TransferOwnershipRequest) GetSkinId() string {
	if x != nil {
		return x.SkinId
	}
	return ""
}

func (x *TransferOwnershipRequest) GetNewOwnerId() string {
	if x != nil {
		return x.NewOwnerId
	}
	return ""
}

func (x *TransferOwnershipRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_shared_proto_inventory_proto protoreflect.FileDescriptor

const file_shared_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cshared/proto/inventory.proto\x12\tinventory\"\xe6\x01\n" +
	"\x04Skin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x16\n" +
	"\x06rarity\x18\x06 \x01(\tR\x06rarity\x12\x1c\n" +
	"\tcondition\x18\a \x01(\tR\tcondition\x12\x19\n" +
	"\bowner_id\x18\b \x01(\tR\aownerId\x12\x1b\n" +
	"\tis_listed\x18\t \x01(\bR\bisListed\"8\n" +
	"\x11CreateSkinRequest\x12#\n" +
	"\x04skin\x18\x01 \x01(\v2\x0f.inventory.SkinR\x04skin\"3\n" +
	"\fSkinResponse\x12#\n" +
	"\x04skin\x18\x01 \x01(\v2\x0f.inventory.SkinR\x04skin\" \n" +
	"\x0eGetSkinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x10ListSkinsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\tis_listed\x18\x02 \x01(\bR\bisListed\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\tR\x06rarity\":\n" +
	"\x11ListSkinsResponse\x12%\n" +
	"\x05skins\x18\x01 \x03(\v2\x0f.inventory.SkinR\x05skins\"8\n" +
	"\x11UpdateSkinRequest\x12#\n" +
	"\x04skin\x18\x01 \x01(\v2\x0f.inventory.SkinR\x04skin\"#\n" +
	"\x11DeleteSkinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x14ToggleListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tis_listed\x18\x02 \x01(\bR\bisListed\"k\n" +
	"\x18TransferOwnershipRequest\x12\x17\n" +
	"\askin_id\x18\x01 \x01(\tR\x06skinId\x12 \n" +
	"\fnew_owner_id\x18\x02 \x01(\tR\n" +
	"newOwnerId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price2\x9f\x05\n" +
	"\x10InventoryService\x12C\n" +
	"\n" +
	"CreateSkin\x12\x1c.inventory.CreateSkinRequest\x1a\x17.inventory.SkinResponse\x12=\n" +
	"\aGetSkin\x12\x19.inventory.GetSkinRequest\x1a\x17.inventory.SkinResponse\x12F\n" +
	"\tListSkins\x12\x1b.inventory.ListSkinsRequest\x1a\x1c.inventory.ListSkinsResponse\x12C\n" +
	"\n" +
	"UpdateSkin\x12\x1c.inventory.UpdateSkinRequest\x1a\x17.inventory.SkinResponse\x12E\n" +
	"\n" +
	"DeleteSkin\x12\x1c.inventory.DeleteSkinRequest\x1a\x19.inventory.DeleteResponse\x12I\n" +
	"\rToggleListing\x12\x1f.inventory.ToggleListingRequest\x1a\x17.inventory.SkinResponse\x12Q\n" +
	"\x11TransferOwnership\x12#.inventory.TransferOwnershipRequest\x1a\x17.inventory.SkinResponse\x12J\n" +
	"\x0fGetSkinsByOwner\x12\x19.inventory.GetSkinRequest\x1a\x1c.inventory.ListSkinsResponse\x12I\n" +
	"\x0eGetListedSkins\x12\x19.inventory.GetSkinRequest\x1a\x1c.inventory.ListSkinsResponseB/Z-cs2-marketplace-microservices/proto/inventoryb\x06proto3"

var (
	file_shared_proto_inventory_proto_rawDescOnce sync.Once
	file_shared_proto_inventory_proto_rawDescData []byte
)

func file_shared_proto_inventory_proto_rawDescGZIP() []byte {
	file_shared_proto_inventory_proto_rawDescOnce.Do(func() {
		file_shared_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_proto_rawDesc), len(file_shared_proto_inventory_proto_rawDesc)))
	})
	return file_shared_proto_inventory_proto_rawDescData
}

var file_shared_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shared_proto_inventory_proto_goTypes = []any{
	(*Skin)(nil),                     // 0: inventory.Skin
	(*CreateSkinRequest)(nil),        // 1: inventory.CreateSkinRequest
	(*SkinResponse)(nil),             // 2: inventory.SkinResponse
	(*GetSkinRequest)(nil),           // 3: inventory.GetSkinRequest
	(*ListSkinsRequest)(nil),         // 4: inventory.ListSkinsRequest
	(*ListSkinsResponse)(nil),        // 5: inventory.ListSkinsResponse
	(*UpdateSkinRequest)(nil),        // 6: inventory.UpdateSkinRequest
	(*DeleteSkinRequest)(nil),        // 7: inventory.DeleteSkinRequest
	(*DeleteResponse)(nil),           // 8: inventory.DeleteResponse
	(*ToggleListingRequest)(nil),     // 9: inventory.ToggleListingRequest
	(*TransferOwnershipRequest)(nil), // 10: inventory.TransferOwnershipRequest
}
var file_shared_proto_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.CreateSkinRequest.skin:type_name -> inventory.Skin
	0,  // 1: inventory.SkinResponse.skin:type_name -> inventory.Skin
	0,  // 2: inventory.ListSkinsResponse.skins:type_name -> inventory.Skin
	0,  // 3: inventory.UpdateSkinRequest.skin:type_name -> inventory.Skin
	1,  // 4: inventory.InventoryService.CreateSkin:input_type -> inventory.CreateSkinRequest
	3,  // 5: inventory.InventoryService.GetSkin:input_type -> inventory.GetSkinRequest
	4,  // 6: inventory.InventoryService.ListSkins:input_type -> inventory.ListSkinsRequest
	6,  // 7: inventory.InventoryService.UpdateSkin:input_type -> inventory.UpdateSkinRequest
	7,  // 8: inventory.InventoryService.DeleteSkin:input_type -> inventory.DeleteSkinRequest
	9,  // 9: inventory.InventoryService.ToggleListing:input_type -> inventory.ToggleListingRequest
	10, // 10: inventory.InventoryService.TransferOwnership:input_type -> inventory.TransferOwnershipRequest
	3,  // 11: inventory.InventoryService.GetSkinsByOwner:input_type -> inventory.GetSkinRequest
	3,  // 12: inventory.InventoryService.GetListedSkins:input_type -> inventory.GetSkinRequest
	2,  // 13: inventory.InventoryService.CreateSkin:output_type -> inventory.SkinResponse
	2,  // 14: inventory.InventoryService.GetSkin:output_type -> inventory.SkinResponse
	5,  // 15: inventory.InventoryService.ListSkins:output_type -> inventory.ListSkinsResponse
	2,  // 16: inventory.InventoryService.UpdateSkin:output_type -> inventory.SkinResponse
	8,  // 17: inventory.InventoryService.DeleteSkin:output_type -> inventory.DeleteResponse
	2,  // 18: inventory.InventoryService.ToggleListing:output_type -> inventory.SkinResponse
	2,  // 19: inventory.InventoryService.TransferOwnership:output_type -> inventory.SkinResponse
	5,  // 20: inventory.InventoryService.GetSkinsByOwner:output_type -> inventory.ListSkinsResponse
	5,  // 21: inventory.InventoryService.GetListedSkins:output_type -> inventory.ListSkinsResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_inventory_proto_init() }
func file_shared_proto_inventory_proto_init() {
	if File_shared_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_inventory_proto_rawDesc), len(file_shared_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_inventory_proto_goTypes,
		DependencyIndexes: file_shared_proto_inventory_proto_depIdxs,
		MessageInfos:      file_shared_proto_inventory_proto_msgTypes,
	}.Build()
	File_shared_proto_inventory_proto = out.File
	file_shared_proto_inventory_proto_goTypes = nil
	file_shared_proto_inventory_proto_depIdxs = nil
}
